import "./globals.css";
// import { Playfair_Display } from "next/font/google";

// const playfair = Playfair_Display({ subsets: ["latin"] });
// const playfair = Playfair_Display({ weight: "400 600 7000" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
